pipeline {
agent any
environment {
    JAVA_HOME="C:/Program Files/Java/jdk-21"
  }
stages {
stage('Clean stage') {
steps {
dir("StockApp") {
bat 'D:/MovableInstallation/apache-maven-3.9.11/bin/mvn clean'
}
}
}

stage('Compile stage') {
steps {
dir("StockApp") {
bat 'D:/MovableInstallation/apache-maven-3.9.11/bin/mvn compile'
}
}
}

stage('Install stage') {
steps {
dir("StockApp") {
bat 'D:/MovableInstallation/apache-maven-3.9.11/bin/mvn install'
}
}
}

}
}
