pipeline {
agent any
environment {
    JAVA_HOME="C:/Program Files/Java/jdk-17"
  }
stages {
stage('Clean stage') {
steps {
dir("StockApp") {
bat 'mvn clean'
}
}
}

stage('Compile stage') {
steps {
dir("StockApp") {
bat 'mvn compile'
}
}
}

stage('Install stage') {
steps {
dir("StockApp") {
bat 'mvn install'
}
}
}

}
}
